spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: st
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
server:
  port: 8081